module(
    name = "kwaque",
    version = "0.0.0",
)

bazel_dep(name = "abseil-cpp", version = "20260526.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")

bazel_dep(name = "buildifier_prebuilt", version = "8.2.0.2", dev_dependency = True)
bazel_dep(name = "rules_buf", version = "0.5.4", dev_dependency = True)

buf = use_extension("@rules_buf//buf:extensions.bzl", "buf", dev_dependency = True)
buf.toolchains(
    sha256 = "18f603d3b418f6a1259da4425b04bbe2fbaf60c2b796b98114d961e8736198b9",
    version = "v1.73.0",
)
use_repo(buf, "rules_buf_toolchains")

bazel_dep(name = "crc32c", version = "1.1.0")
bazel_dep(name = "fmt", version = "12.1.0")
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "liburing", version = "2.14")
bazel_dep(name = "lz4", version = "1.9.4")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "protobuf", version = "33.5")
bazel_dep(name = "ragel", version = "26.04.0-20260414092900-8841e561489e")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "xxhash", version = "0.8.3.bcr.1")
bazel_dep(name = "yaml-cpp", version = "0.8.0")
bazel_dep(name = "zlib", version = "1.3.1.bcr.6")
bazel_dep(
    name = "rules_boost",
    repo_name = "com_github_nelhage_rules_boost",
)
archive_override(
    module_name = "rules_boost",
    integrity = "sha256-wQsxOxZh1tluc6AXj+ncsYhBSl03uC+hPhBrU6JkupI=",
    patch_strip = 1,
    patches = [
        "//bazel/thirdparty:rules-boost-license.patch",
        "//bazel/thirdparty:rules-boost-uuid-value.patch",
    ],
    strip_prefix = "rules_boost-f5b0f8c904f2487d8f5a9a956d4388724e627210",
    urls = ["https://github.com/nelhage/rules_boost/archive/f5b0f8c904f2487d8f5a9a956d4388724e627210.tar.gz"],
)

boost_dependencies = use_extension(
    "@com_github_nelhage_rules_boost//:boost/repositories.bzl",
    "non_module_dependencies",
)
use_repo(boost_dependencies, "boost")

single_version_override(
    module_name = "abseil-cpp",
    patch_strip = 1,
    patches = ["//bazel/thirdparty:abseil-clang-23-lifetime-capture.patch"],
)

single_version_override(
    module_name = "crc32c",
    patch_strip = 1,
    patches = ["//bazel/thirdparty:crc32c-license.patch"],
)

single_version_override(
    module_name = "liburing",
    patch_strip = 1,
    patches = [
        "//bazel/thirdparty:liburing.patch",
        "//bazel/thirdparty:liburing-license.patch",
    ],
)

single_version_override(
    module_name = "lz4",
    patch_strip = 1,
    patches = [
        "//bazel/thirdparty:lz4-namespace-xxhash.patch",
        "//bazel/thirdparty:lz4-license.patch",
    ],
)

single_version_override(
    module_name = "protobuf",
    patch_strip = 1,
    patches = [
        "//bazel/thirdparty:protobuf-parse-exception-safety.patch",
        "//bazel/thirdparty:protobuf-accessor-exception-safety.patch",
    ],
)

single_version_override(
    module_name = "xxhash",
    patch_strip = 1,
    patches = [
        "//bazel/thirdparty:xxhash-dispatch.patch",
        "//bazel/thirdparty:xxhash-license.patch",
    ],
)

single_version_override(
    module_name = "yaml-cpp",
    patch_strip = 1,
    patches = ["//bazel/thirdparty:yaml-cpp-license.patch"],
)

native_dependencies = use_extension("//bazel:extensions.bzl", "native_dependencies")
use_repo(
    native_dependencies,
    "aarch64_sysroot",
    "c-ares",
    "hwloc",
    "lksctp",
    "openssl",
    "seastar",
    "unordered_dense",
    "x86_64_sysroot",
)

bazel_dep(name = "toolchains_llvm", version = "1.10.0", dev_dependency = True)

llvm = use_extension(
    "@toolchains_llvm//toolchain/extensions:llvm.bzl",
    "llvm",
    dev_dependency = True,
)
llvm.toolchain(
    name = "current_llvm_toolchain",
    cxx_standard = {"": "c++23"},
    extra_compile_flags = {
        "linux-aarch64": ["-march=armv8-a+crc+crypto"],
        "linux-x86_64": ["-march=westmere"],
    },
    llvm_version = "23.1.2",
    sha256 = {
        "linux-aarch64": "38f9123ac31b954164d5cee1664ecc45a4db2e9795247635a46d919f2a1fb6ea",
        "linux-x86_64": "5581ff63eb2d1ec8a2cf61847240465a4e177f2ece3d663ef3f43e309d28eb53",
    },
    urls = {
        "linux-aarch64": ["https://github.com/redpanda-data/llvm-project/releases/download/llvmorg-23.1.2/llvm-23.1.2-debian-11-aarch64-2026-09-28.tar.zst"],
        "linux-x86_64": ["https://github.com/redpanda-data/llvm-project/releases/download/llvmorg-23.1.2/llvm-23.1.2-debian-11-x86_64-2026-09-28.tar.zst"],
    },
)
llvm.sysroot(
    name = "current_llvm_toolchain",
    label = "@x86_64_sysroot//sysroot:sysroot",
    targets = ["linux-x86_64"],
)
llvm.sysroot(
    name = "current_llvm_toolchain",
    label = "@aarch64_sysroot//sysroot:sysroot",
    targets = ["linux-aarch64"],
)
use_repo(llvm, "current_llvm_toolchain", "current_llvm_toolchain_llvm")

register_toolchains(
    "@current_llvm_toolchain//:all",
    dev_dependency = True,
)
