#include "proto/kwaque/common/v1/build_info.pb.h"
#include "proto/kwaque/common/v1/capability.pb.h"
#include "proto/kwaque/common/v1/error.pb.h"
#include "proto/kwaque/common/v1/identity.pb.h"
#include "proto/kwaque/control/v1/handshake.pb.h"
#include "proto/kwaque/control/v1/redirect.pb.h"
#include "src/base/invariant.h"
#include "src/codec/framing_internal.h"
#include "src/codec/staging.h"
#include "src/protocol/control_internal.h"
#include "src/protocol/control_memory.h"

#include <seastar/core/coroutine.hh>
#include <seastar/core/temporary_buffer.hh>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>

#include <concepts>
#include <cstdint>
#include <exception>
#include <memory>
#include <optional>
#include <span>
#include <type_traits>
#include <utility>

namespace kwaque::protocol {
namespace {
namespace common = kwaque::common::v1;
namespace native = kwaque::control::v1;
using codec::detail::framing::add_charge;
using codec::detail::framing::encode_error;

class filler final {
public:
    filler(codec::cooperative_work& work, codec::error anchor)
      : work_(work)
      , anchor_(anchor) {}
    codec::result<void> poll() const noexcept { return work_.poll(anchor_); }
    seastar::future<codec::result<void>>
    leaf(byte_count bytes, item_count items, auto action) {
        const auto ready = co_await work_.admit(bytes, items, anchor_);
        if (!ready) co_return codec::failure(ready.error());
        if (auto poll = work_.poll(anchor_); !poll)
            co_return codec::failure(poll.error());
        action();
        co_return work_.poll(anchor_);
    }
    seastar::future<codec::result<void>>
    build(common::BuildInfo& output, const build_information& input) {
        if (!input.version.empty()) {
            auto ready = co_await leaf(
              byte_count{input.version.size()}, item_count{1}, [&] {
                  output.set_version(input.version);
              });
            if (!ready) co_return ready;
        }
        if (!input.revision.empty()) {
            auto ready = co_await leaf(
              byte_count{input.revision.size()}, item_count{1}, [&] {
                  output.set_revision(input.revision);
              });
            if (!ready) co_return ready;
        }
        if (!input.build_mode.empty()) {
            auto ready = co_await leaf(
              byte_count{input.build_mode.size()}, item_count{1}, [&] {
                  output.set_build_mode(input.build_mode);
              });
            if (!ready) co_return ready;
        }
        co_return work_.poll(anchor_);
    }
    seastar::future<codec::result<void>> capabilities(
      common::Capabilities& output, const control_capabilities& input) {
        for (const auto value : input.protocol_versions) {
            auto ready = co_await leaf(
              byte_count{sizeof(value)}, item_count{1}, [&] {
                  output.add_protocol_versions(value);
              });
            if (!ready) co_return ready;
        }
        for (const auto& value : input.formats) {
            auto ready = co_await leaf(byte_count{32}, item_count{5}, [&] {
                auto* format = output.add_formats();
                format->set_family(value.family);
                format->set_oldest_readable(value.oldest_readable);
                format->set_current(value.current);
                format->set_supported_features(value.supported_features);
            });
            if (!ready) co_return ready;
        }
        for (const auto value : input.compression_codecs) {
            auto ready = co_await leaf(
              byte_count{sizeof(value)}, item_count{1}, [&] {
                  output.add_compression_codecs(value);
              });
            if (!ready) co_return ready;
        }
        co_return co_await leaf(byte_count{32}, item_count{5}, [&] {
            output.set_max_frame_body_bytes(
              static_cast<std::uint32_t>(input.max_frame_body_bytes.value()));
            output.set_max_expanded_batch_bytes(
              static_cast<std::uint32_t>(
                input.max_expanded_batch_bytes.value()));
            output.set_max_header_bytes(
              static_cast<std::uint32_t>(input.max_header_bytes.value()));
            output.set_max_record_bytes(
              static_cast<std::uint32_t>(input.max_record_bytes.value()));
            output.set_max_original_records(
              static_cast<std::uint32_t>(input.max_original_records.value()));
        });
    }

private:
    codec::cooperative_work& work_;
    codec::error anchor_;
};

// All identities are already checked. Generated byte setters copy the exact
// opaque representation; neither ordering nor transport IDs reinterpret it.
auto id_data(const auto& id) {
    return reinterpret_cast<const char*>(id.bytes().data());
}
void routing(common::RoutingContext& output, const routing_context& input) {
    output.set_topic_id(id_data(input.topic), model::topic_id::width);
    output.set_range_id(id_data(input.range), model::range_id::width);
    output.set_segment_id(id_data(input.segment), model::segment_id::width);
    output.set_routing_epoch(input.routing_epoch.value());
    output.set_segment_generation(input.generation.value());
}

template<typename Message, typename Value>
seastar::future<codec::result<void>>
fill(Message& output, const Value& input, filler& writer) {
    auto ready = co_await writer.leaf(byte_count{128}, item_count{8}, [&] {
        if constexpr (std::same_as<Value, handshake_request>) {
            output.set_peer_kind(static_cast<native::PeerKind>(input.peer));
            if (input.expected_cluster)
                output.set_expected_cluster_id(
                  id_data(*input.expected_cluster), model::cluster_id::width);
            if (input.broker)
                output.set_broker_id(
                  id_data(*input.broker), model::broker_id::width);
            static_cast<void>(output.mutable_build());
            static_cast<void>(output.mutable_capabilities());
        } else if constexpr (std::same_as<Value, handshake_response>) {
            output.set_cluster_id(
              id_data(input.cluster), model::cluster_id::width);
            output.set_broker_id(
              id_data(input.broker), model::broker_id::width);
            static_cast<void>(output.mutable_build());
            static_cast<void>(output.mutable_capabilities());
        } else if constexpr (std::same_as<Value, redirect_control>) {
            routing(*output.mutable_destination(), input.destination);
            output.set_broker_id(
              id_data(input.broker), model::broker_id::width);
            output.mutable_endpoint()->set_port(input.endpoint.port);
            output.set_reason(static_cast<common::ErrorCode>(input.reason));
        } else {
            output.set_code(static_cast<common::ErrorCode>(input.code));
            if (input.observed)
                routing(*output.mutable_observed(), *input.observed);
        }
    });
    if (!ready) co_return ready;
    if (auto poll = writer.poll(); !poll)
        co_return codec::failure(poll.error());
    if constexpr (
      std::same_as<Value, handshake_request>
      || std::same_as<Value, handshake_response>) {
        ready = co_await writer.build(*output.mutable_build(), input.build);
        if (!ready) co_return ready;
        if (auto poll = writer.poll(); !poll)
            co_return codec::failure(poll.error());
        co_return co_await writer.capabilities(
          *output.mutable_capabilities(), input.capabilities);
    } else if constexpr (std::same_as<Value, redirect_control>) {
        co_return co_await writer.leaf(
          byte_count{input.endpoint.host.size()}, item_count{1}, [&] {
              output.mutable_endpoint()->set_host(input.endpoint.host);
          });
    } else {
        if (input.reason)
            co_return co_await writer.leaf(
              byte_count{input.reason->size()}, item_count{1}, [&] {
                  output.set_reason(*input.reason);
              });
        co_return codec::result<void>{};
    }
}

template<typename Message, typename Value>
seastar::future<codec::result<bytes::fragmented_buffer>> encode(
  const Value& value,
  detail::control_layout layout,
  codec::cooperative_work& work,
  codec::operation_usage live,
  byte_count parent_remaining,
  bytes::allocation_charge_fn charge,
  codec::field_context context) {
    const auto anchor = encode_error(errc::success, context);
    // Native size/write/destruction also inspect absent singular fields. The
    // fixed root/BuildInfo remainder fits one schema's field-state bound.
    const item_count native_items{
      layout.units.value() + detail::control_scope_fields};
    const auto* schema = detail::schema_for(layout.kind);
    const auto cost = detail::bound_control_parse(
      schema->message, layout.wire_bytes, work.policy(), charge, context);
    if (!cost) co_return codec::failure(cost.error());
    // Fresh setters allocate only the known graph and one string per emitted
    // field, a subset of the parse bound. Output owns a second contiguous copy
    // plus one prepared descriptor; its backing is frozen by the byte builder.
    const byte_count descriptor_request{
      bytes::fragmented_buffer::fragment_descriptor_size()};
    const auto descriptor = charge(descriptor_request);
    if (descriptor < descriptor_request)
        co_return codec::failure(encode_error(errc::invalid_argument, context));
    if (!work.policy().validate_allocation(descriptor))
        co_return codec::failure(
          encode_error(errc::resource_exhausted, context));
    const auto peak = layout.storage.value() + cost->generated_peak.value()
                      + 2U * cost->input_copy.value() + descriptor.value();
    if (peak > codec::limits::defaults().config().max_metadata_bytes.value())
        co_return codec::failure(
          encode_error(errc::resource_exhausted, context));
    for (auto amount : {layout.storage, cost->generated_peak}) {
        if (
          auto added = add_charge(live.decoded_metadata, amount, context);
          !added)
            co_return codec::failure(added.error());
    }
    if (
      auto added = add_charge(live.staged_output, cost->input_copy, context);
      !added)
        co_return codec::failure(added.error());
    auto complete = live;
    if (
      auto added = add_charge(
        complete.staged_output, cost->input_copy, context);
      !added)
        co_return codec::failure(added.error());
    if (
      auto added = add_charge(
        complete.payload_bookkeeping, descriptor, context);
      !added)
        co_return codec::failure(added.error());
    const auto admitted = work.policy().remaining_operation_bytes(
      complete, parent_remaining);
    if (!admitted)
        co_return codec::failure(
          codec::detail::allocation_cost_error(
            admitted.error(), context, context.origin));
    // Admit the indivisible native leaf before creating anything whose cleanup
    // needs this same quantum, including an allocation-failed partial message.
    if (
      auto ready = co_await work.admit(layout.wire_bytes, native_items, anchor);
      !ready)
        co_return codec::failure(ready.error());
    if (auto ready = work.poll(anchor); !ready)
        co_return codec::failure(ready.error());
    std::unique_ptr<Message> generated;
    std::optional<seastar::temporary_buffer<char>> wire;
    std::optional<bytes::fragmented_buffer> output;
    std::optional<codec::error> failed;
    std::exception_ptr exception;
    try {
        do {
            generated = std::make_unique<Message>();
            filler writer{work, anchor};
            auto filled = co_await fill(*generated, value, writer);
            if (!filled) {
                failed = filled.error();
                break;
            }
            if (
              auto ready = co_await work.admit(
                layout.wire_bytes, native_items, anchor);
              !ready) {
                failed = ready.error();
                break;
            }
            if (auto ready = work.poll(anchor); !ready) {
                failed = ready.error();
                break;
            }
            const auto size = generated->ByteSizeLong();
            KWAQUE_INVARIANT(
              invariant_id{"KQ-CONTROL-WRITER-SIZE"},
              size == layout.wire_bytes.value(),
              "generated size differs from admitted control layout");
            if (auto ready = co_await work.checkpoint(anchor); !ready) {
                failed = ready.error();
                break;
            }
            if (auto ready = work.poll(anchor); !ready) {
                failed = ready.error();
                break;
            }
            wire.emplace(size);
            if (
              auto ready = co_await work.admit(
                layout.wire_bytes, native_items, anchor);
              !ready) {
                failed = ready.error();
                break;
            }
            if (auto ready = work.poll(anchor); !ready) {
                failed = ready.error();
                break;
            }
            // The private message is immutable after sizing. The public
            // cached-size stream API avoids an unaccounted second size pass.
            {
                google::protobuf::io::ArrayOutputStream raw{
                  wire->get_write(), static_cast<int>(size)};
                google::protobuf::io::CodedOutputStream stream{&raw};
                generated->SerializeWithCachedSizes(&stream);
                stream.Trim();
                KWAQUE_INVARIANT(
                  invariant_id{"KQ-CONTROL-WRITER-END"},
                  !stream.HadError()
                    && stream.ByteCount() == static_cast<int>(size)
                    && raw.ByteCount() == static_cast<std::int64_t>(size),
                  "generated serialization changed the admitted extent");
            }
            if (
              auto ready = co_await work.admit(
                work.byte_quantum(), work.item_quantum(), anchor);
              !ready) {
                failed = ready.error();
                break;
            }
            if (auto ready = work.poll(anchor); !ready) {
                failed = ready.error();
                break;
            }
            auto published = codec::assemble_buffer(
              std::span<const char>{wire->get(), size},
              {},
              work.policy(),
              layout.wire_bytes,
              live,
              parent_remaining,
              charge,
              context);
            if (!published) {
                failed = published.error();
                break;
            }
            output.emplace(std::move(*published));
        } while (false);
    } catch (...) {
        exception = std::current_exception();
    }
    if (generated) {
        co_await work.drain_inline(layout.wire_bytes, native_items);
        generated.reset();
        co_await work.drain_inline(work.byte_quantum(), work.item_quantum());
    }
    if (wire) {
        co_await work.drain_inline(byte_count{}, item_count{1});
        wire.reset();
    }
    if (!failed && !exception) {
        if (auto ready = work.poll(anchor); !ready) failed = ready.error();
    }
    if (failed || exception) {
        if (output) {
            co_await work.drain_inline(
              work.byte_quantum(), work.item_quantum());
            output.reset();
        }
        if (exception) std::rethrow_exception(exception);
        co_return codec::failure(*failed);
    }
    co_return std::move(*output);
}
} // namespace

seastar::future<codec::result<bytes::fragmented_buffer>>
detail::encode_control_checked(
  const control_data& value,
  control_layout layout,
  codec::cooperative_work& work,
  codec::operation_usage live,
  byte_count parent,
  bytes::allocation_charge_fn charge,
  codec::field_context context) {
    switch (layout.kind) {
    case frame_kind::handshake_request:
        return encode<native::HandshakeRequest>(
          std::get<handshake_request>(value),
          layout,
          work,
          live,
          parent,
          charge,
          context);
    case frame_kind::handshake_response:
        return encode<native::HandshakeResponse>(
          std::get<handshake_response>(value),
          layout,
          work,
          live,
          parent,
          charge,
          context);
    case frame_kind::redirect:
        return encode<native::Redirect>(
          std::get<redirect_control>(value),
          layout,
          work,
          live,
          parent,
          charge,
          context);
    case frame_kind::error:
        return encode<common::Error>(
          std::get<error_control>(value),
          layout,
          work,
          live,
          parent,
          charge,
          context);
    case frame_kind::submitted_batch:
    case frame_kind::assigned_batch:
        break;
    }
    return seastar::make_ready_future<codec::result<bytes::fragmented_buffer>>(
      codec::failure(encode_error(errc::invalid_argument, context)));
}

seastar::future<codec::result<bytes::fragmented_buffer>> encode_control(
  const control& value,
  codec::cooperative_work& work,
  codec::operation_usage other_live,
  byte_count parent,
  bytes::allocation_charge_fn charge,
  codec::field_context context) {
    const auto layout = co_await detail::inspect_control_value(
      value.data(), work, charge, context);
    if (!layout) co_return codec::failure(layout.error());
    if (auto ready = work.poll(encode_error(errc::success, context)); !ready)
        co_return codec::failure(ready.error());
    auto encoded = co_await detail::encode_control_checked(
      value.data(), *layout, work, other_live, parent, charge, context);
    if (!encoded) co_return codec::failure(encoded.error());
    if (auto ready = work.poll(encode_error(errc::success, context)); !ready) {
        co_await work.drain_inline(work.byte_quantum(), work.item_quantum());
        encoded = codec::failure(ready.error());
        co_return codec::failure(ready.error());
    }
    co_return std::move(*encoded);
}
} // namespace kwaque::protocol
