"""Link-time observation is confined to isolated native qualification probes."""

ALLOCATION_OBSERVER_LINKOPTS = select({
    "//bazel:system_allocator": [],
    "//conditions:default": [
        "-Wl,--wrap=malloc",
        "-Wl,--wrap=calloc",
        "-Wl,--wrap=realloc",
        "-Wl,--wrap=memalign",
        "-Wl,--wrap=aligned_alloc",
        "-Wl,--wrap=posix_memalign",
        "-Wl,--wrap=free",
        "-Wl,--wrap=cfree",
        "-Wl,--wrap=free_sized",
        "-Wl,--wrap=free_aligned_sized",
        "-Wl,--wrap=_Znwm",
        "-Wl,--wrap=_ZnwmRKSt9nothrow_t",
        "-Wl,--wrap=_ZnwmSt11align_val_t",
        "-Wl,--wrap=_ZnwmSt11align_val_tRKSt9nothrow_t",
        "-Wl,--wrap=_Znam",
        "-Wl,--wrap=_ZnamRKSt9nothrow_t",
        "-Wl,--wrap=_ZnamSt11align_val_t",
        "-Wl,--wrap=_ZnamSt11align_val_tRKSt9nothrow_t",
        "-Wl,--wrap=_ZdlPv",
        "-Wl,--wrap=_ZdlPvm",
        "-Wl,--wrap=_ZdlPvRKSt9nothrow_t",
        "-Wl,--wrap=_ZdlPvSt11align_val_t",
        "-Wl,--wrap=_ZdlPvmSt11align_val_t",
        "-Wl,--wrap=_ZdlPvSt11align_val_tRKSt9nothrow_t",
        "-Wl,--wrap=_ZdaPv",
        "-Wl,--wrap=_ZdaPvm",
        "-Wl,--wrap=_ZdaPvRKSt9nothrow_t",
        "-Wl,--wrap=_ZdaPvSt11align_val_t",
        "-Wl,--wrap=_ZdaPvmSt11align_val_t",
        "-Wl,--wrap=_ZdaPvSt11align_val_tRKSt9nothrow_t",
    ],
})
